name: Download Manifest

on:
  # Run daily
  schedule:
    - cron: '30 12 * * *'
  # Manual run, for debugging purposes.
  workflow_dispatch:
    inputs: {}

jobs:
  Download_Manifest:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        major: [15, 16, 17]
        type: [release, pre]
        include:
          - major: 18
            type: pre
    steps:
      - id: checkout
        uses: actions/checkout@v2
        continue-on-error: true
        with:
          ref: ${{ matrix.type }}-${{ matrix.major }}
      - uses: actions/checkout@v2
        if: steps.checkout.conclusion == 'failure'
        with:
          ref: master
      - if: steps.checkout.conclusion == 'failure'
        run: git switch --orphan "${{ matrix.type }}-${{ matrix.major }}"

      - name: Remove old channels and manifests
        run: rm -f raw_channel.json channel.json raw_manifest.json manifest.json

      - name: Downloads current latest channels
        run: |
          TYPE='${{ matrix.type }}'
          if [[ '${{ matrix.major }}' -ge 18 && '${{ matrix.type }}' == 'pre' ]]; then
            # For whatever reason, on 18+, the name of the channel for
            # pre-release became "insiders", and they also changed the URL...
            TYPE=insiders
          fi
          curl -L https://aka.ms/vs/${{ matrix.major }}/$TYPE/channel -o raw_channel.json
          # Make a version that's easy to diff and view.
          jq . raw_channel.json > channel.json

      - name: Check if build is internal MS-only
        id: check-internal-domain
        run: |
          url=$(jq -r '.channelItems | map(select(.type == "Manifest")) | .[0].payloads[0].url' raw_channel.json)
          echo "URL is '${url}'"
          if [[ "$url" == *"vsdrop.corp.microsoft.com"* ]]; then
            echo "INTERNAL_URL=true" >> $GITHUB_OUTPUT
          fi
      - name: Download current latest manifests
        if: steps.check-internal-domain.outputs.INTERNAL_URL != 'true'
        run: |
          url=$(jq -r '.channelItems | map(select(.type == "Manifest")) | .[0].payloads[0].url' raw_channel.json)
          echo $url
          curl -L $url -o raw_manifest.json
          jq . raw_manifest.json > manifest.json

      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: Update manifest
          push: true
          new_branch: ${{ matrix.type }}-${{ matrix.major }}
